name: Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        appdir: "advanced-integration"
    - name: Install JS Dependencies
      run: npm install
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
